[package]
name = "cranpose-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description = "Testing utilities and harness for Cranpose"

[features]
default = []
desktop-robot = [
    "cranpose/desktop",
    "cranpose/renderer-wgpu",
    "cranpose/robot",
]

[dependencies]
cranpose-core = { workspace = true }
cranpose-foundation = { workspace = true }
cranpose-ui = { workspace = true, features = ["test-helpers"] }
cranpose-app-shell = { workspace = true }
cranpose-render-common = { workspace = true }
cranpose-ui-graphics = { workspace = true }

# Dependencies for real app testing
cranpose = { workspace = true, default-features = false }

[dev-dependencies]
cranpose-macros = { workspace = true }
cranpose-ui-layout = { workspace = true }

 
