[package]
name = "cranpose-ui-graphics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description = "Pure math/data for drawing & units in Cranpose"
autotests = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
arrayvec = "0.7.8"
bytemuck = { workspace = true }
cursor-icon = { workspace = true }
foldhash = "0.2.0"
thiserror = "2.0.20"

[features]
default = []

[[test]]
name = "integration"
path = "tests/integration.rs"
