// Generated by `tools/compose-twin/generate_matrix.py` from
// `tools/compose-twin/matrix.toml`. Do not edit: change the description and
// generate again.
//
// The Compose half of the modifier matrix (issue #905).

package dev.cranpose.twin

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clipToBounds
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.unit.dp

private val Red = Color(0.85f, 0.35f, 0.3f, 1.0f)
private val Blue = Color(0.3f, 0.55f, 0.9f, 1.0f)
private val Green = Color(0.35f, 0.8f, 0.45f, 1.0f)
private val Gold = Color(0.95f, 0.75f, 0.25f, 1.0f)
private val Dim = Color(0.22f, 0.24f, 0.3f, 1.0f)

/** Every matrix frame, in the order Cranpose captures them. */
val MATRIX_FRAMES: List<TwinFrame> = listOf(
    TwinFrame("matrix-chains2-00", 1.0f) { chains2_00() },
    TwinFrame("matrix-chains2-00@2.625", 2.625f) { chains2_00() },
    TwinFrame("matrix-chains2-01", 1.0f) { chains2_01() },
    TwinFrame("matrix-chains2-01@2.625", 2.625f) { chains2_01() },
    TwinFrame("matrix-chains2-02", 1.0f) { chains2_02() },
    TwinFrame("matrix-chains2-02@2.625", 2.625f) { chains2_02() },
    TwinFrame("matrix-chains2-03", 1.0f) { chains2_03() },
    TwinFrame("matrix-chains2-03@2.625", 2.625f) { chains2_03() },
    TwinFrame("matrix-chains2-04", 1.0f) { chains2_04() },
    TwinFrame("matrix-chains2-04@2.625", 2.625f) { chains2_04() },
    TwinFrame("matrix-chains2-05", 1.0f) { chains2_05() },
    TwinFrame("matrix-chains2-05@2.625", 2.625f) { chains2_05() },
    TwinFrame("matrix-chains3-00", 1.0f) { chains3_00() },
    TwinFrame("matrix-chains3-00@2.625", 2.625f) { chains3_00() },
    TwinFrame("matrix-chains3-01", 1.0f) { chains3_01() },
    TwinFrame("matrix-chains3-01@2.625", 2.625f) { chains3_01() },
    TwinFrame("matrix-chains3-02", 1.0f) { chains3_02() },
    TwinFrame("matrix-chains3-02@2.625", 2.625f) { chains3_02() },
    TwinFrame("matrix-chains3-03", 1.0f) { chains3_03() },
    TwinFrame("matrix-chains3-03@2.625", 2.625f) { chains3_03() },
    TwinFrame("matrix-chains3-04", 1.0f) { chains3_04() },
    TwinFrame("matrix-chains3-04@2.625", 2.625f) { chains3_04() },
    TwinFrame("matrix-chains3-05", 1.0f) { chains3_05() },
    TwinFrame("matrix-chains3-05@2.625", 2.625f) { chains3_05() },
    TwinFrame("matrix-chains3-06", 1.0f) { chains3_06() },
    TwinFrame("matrix-chains3-06@2.625", 2.625f) { chains3_06() },
    TwinFrame("matrix-chains3-07", 1.0f) { chains3_07() },
    TwinFrame("matrix-chains3-07@2.625", 2.625f) { chains3_07() },
    TwinFrame("matrix-chains3-08", 1.0f) { chains3_08() },
    TwinFrame("matrix-chains3-08@2.625", 2.625f) { chains3_08() },
    TwinFrame("matrix-chains3-09", 1.0f) { chains3_09() },
    TwinFrame("matrix-chains3-09@2.625", 2.625f) { chains3_09() },
    TwinFrame("matrix-chains3-10", 1.0f) { chains3_10() },
    TwinFrame("matrix-chains3-10@2.625", 2.625f) { chains3_10() },
    TwinFrame("matrix-chains3-11", 1.0f) { chains3_11() },
    TwinFrame("matrix-chains3-11@2.625", 2.625f) { chains3_11() },
    TwinFrame("matrix-chains3-12", 1.0f) { chains3_12() },
    TwinFrame("matrix-chains3-12@2.625", 2.625f) { chains3_12() },
    TwinFrame("matrix-chains3-13", 1.0f) { chains3_13() },
    TwinFrame("matrix-chains3-13@2.625", 2.625f) { chains3_13() },
    TwinFrame("matrix-text2-00", 1.0f) { text2_00() },
    TwinFrame("matrix-text2-01", 1.0f) { text2_01() },
    TwinFrame("matrix-text2-02", 1.0f) { text2_02() },
    TwinFrame("matrix-rows-00", 1.0f) { rows_00() },
    TwinFrame("matrix-rows-00@2.625", 2.625f) { rows_00() },
    TwinFrame("matrix-rows-01", 1.0f) { rows_01() },
    TwinFrame("matrix-rows-01@2.625", 2.625f) { rows_01() },
    TwinFrame("matrix-columns-00", 1.0f) { columns_00() },
    TwinFrame("matrix-columns-00@2.625", 2.625f) { columns_00() },
    TwinFrame("matrix-columns-01", 1.0f) { columns_01() },
    TwinFrame("matrix-columns-01@2.625", 2.625f) { columns_01() },
    TwinFrame("matrix-boxes-00", 1.0f) { boxes_00() },
    TwinFrame("matrix-boxes-00@2.625", 2.625f) { boxes_00() },
    TwinFrame("matrix-weights-00", 1.0f) { weights_00() },
    TwinFrame("matrix-weights-00@2.625", 2.625f) { weights_00() },
)

@Composable
private fun Probe(modifier: Modifier) {
    Box(modifier) { Block(20, 14, Green) }
}

@Composable
private fun Block(width: Int, height: Int, color: Color) {
    Box(Modifier.size(width.dp, height.dp).background(color))
}

@Composable
private fun RowProbe(arrangement: Arrangement.Horizontal, alignment: Alignment.Vertical) {
    Row(Modifier.size(121.dp, 65.dp).background(Dim), arrangement, alignment) {
        Block(16, 12, Red); Block(22, 30, Blue); Block(12, 20, Gold)
    }
}

@Composable
private fun ColumnProbe(arrangement: Arrangement.Vertical, alignment: Alignment.Horizontal) {
    Column(Modifier.size(89.dp, 97.dp).background(Dim), arrangement, alignment) {
        Block(12, 16, Red); Block(30, 22, Blue); Block(20, 12, Gold)
    }
}

@Composable
private fun BoxProbe(alignment: Alignment) {
    Box(Modifier.size(121.dp, 91.dp).background(Dim), contentAlignment = alignment) {
        Block(30, 20, Red)
    }
}

private val BlockColors = listOf(Red, Blue, Gold, Green)

@Composable
private fun WeightsProbe(children: List<Pair<Float, Boolean>>) {
    Row(Modifier.size(121.dp, 40.dp).background(Dim)) {
        children.forEachIndexed { at, (weight, fill) ->
            val color = BlockColors[at % BlockColors.size]
            if (weight == 0f) {
                Block(18, 24, color)
            } else {
                Box(Modifier.weight(weight, fill).width(10.dp).height(24.dp).background(color))
            }
        }
    }
}

@Composable
private fun chains2_00() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).size(64.dp, 44.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).clipToBounds()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).graphicsLayer { alpha = 0.5f }) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).offset(7.dp, 5.dp)) }
        }
    }
}

@Composable
private fun chains2_01() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).graphicsLayer { alpha = 0.5f }) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).graphicsLayer { alpha = 0.5f }) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).padding(6.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).width(52.dp)) }
        }
    }
}

@Composable
private fun chains2_02() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).graphicsLayer { alpha = 0.5f }) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).clipToBounds()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).graphicsLayer { alpha = 0.5f }) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).background(Red)) }
        }
    }
}

@Composable
private fun chains2_03() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.width(52.dp).graphicsLayer { alpha = 0.5f }) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().width(52.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().graphicsLayer { alpha = 0.5f }) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).padding(6.dp)) }
        }
    }
}

@Composable
private fun chains2_04() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).size(64.dp, 44.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).graphicsLayer { alpha = 0.5f }) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().offset(7.dp, 5.dp)) }
        }
    }
}

@Composable
private fun chains2_05() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().graphicsLayer { alpha = 0.5f }) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.background(Red)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.graphicsLayer { alpha = 0.5f }.clipToBounds()) }
        }
    }
}

@Composable
private fun chains3_00() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Red).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Red).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Red).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Red).offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Red).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Blue).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Blue).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Blue).fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Blue).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).background(Blue).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).size(64.dp, 44.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).size(64.dp, 44.dp).background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).size(64.dp, 44.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).size(64.dp, 44.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).size(64.dp, 44.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).fillMaxWidth().background(Red)) }
        }
    }
}

@Composable
private fun chains3_01() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).fillMaxWidth().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).fillMaxWidth().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).fillMaxWidth().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).fillMaxWidth().clipToBounds()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).offset(7.dp, 5.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).offset(7.dp, 5.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).offset(7.dp, 5.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).offset(7.dp, 5.dp).fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).offset(7.dp, 5.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).clipToBounds().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).clipToBounds().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).clipToBounds().size(64.dp, 44.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).clipToBounds().fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.padding(6.dp).clipToBounds().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).padding(6.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).padding(6.dp).size(64.dp, 44.dp)) }
        }
    }
}

@Composable
private fun chains3_02() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).padding(6.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).padding(6.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).padding(6.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).background(Blue).padding(6.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).background(Blue).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).background(Blue).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).background(Blue).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).background(Blue).clipToBounds()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).size(64.dp, 44.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).size(64.dp, 44.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).size(64.dp, 44.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).size(64.dp, 44.dp).offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).size(64.dp, 44.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).fillMaxWidth().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).fillMaxWidth().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).fillMaxWidth().size(64.dp, 44.dp)) }
        }
    }
}

@Composable
private fun chains3_03() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).fillMaxWidth().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).fillMaxWidth().clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).offset(7.dp, 5.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).offset(7.dp, 5.dp).background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).offset(7.dp, 5.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).offset(7.dp, 5.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).offset(7.dp, 5.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).clipToBounds().padding(6.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).clipToBounds().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).clipToBounds().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).clipToBounds().fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Red).clipToBounds().offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).padding(6.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).padding(6.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).padding(6.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).padding(6.dp).offset(7.dp, 5.dp)) }
        }
    }
}

@Composable
private fun chains3_04() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).padding(6.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).background(Red).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).background(Red).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).background(Red).fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).background(Red).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).background(Red).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).size(64.dp, 44.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).size(64.dp, 44.dp).background(Red)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).size(64.dp, 44.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).size(64.dp, 44.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).size(64.dp, 44.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).fillMaxWidth().padding(6.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).fillMaxWidth().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).fillMaxWidth().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).fillMaxWidth().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).fillMaxWidth().clipToBounds()) }
        }
    }
}

@Composable
private fun chains3_05() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).offset(7.dp, 5.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).offset(7.dp, 5.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).offset(7.dp, 5.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).offset(7.dp, 5.dp).fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).offset(7.dp, 5.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).clipToBounds().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).clipToBounds().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).clipToBounds().size(64.dp, 44.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).clipToBounds().fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.background(Blue).clipToBounds().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).padding(6.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).padding(6.dp).background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).padding(6.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).padding(6.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).padding(6.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Red).padding(6.dp)) }
        }
    }
}

@Composable
private fun chains3_06() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Red).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Red).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Red).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Red).clipToBounds()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Blue).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Blue).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Blue).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Blue).offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).background(Blue).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).fillMaxWidth().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).fillMaxWidth().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).fillMaxWidth().background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).fillMaxWidth().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).fillMaxWidth().clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).offset(7.dp, 5.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).offset(7.dp, 5.dp).background(Red)) }
        }
    }
}

@Composable
private fun chains3_07() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).offset(7.dp, 5.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).offset(7.dp, 5.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).offset(7.dp, 5.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).clipToBounds().padding(6.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).clipToBounds().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).clipToBounds().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).clipToBounds().fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.size(64.dp, 44.dp).clipToBounds().offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().padding(6.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().padding(6.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().padding(6.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().padding(6.dp).offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().padding(6.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Red).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Red).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Red).size(64.dp, 44.dp)) }
        }
    }
}

@Composable
private fun chains3_08() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Red).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Red).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Blue).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Blue).background(Red)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Blue).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Blue).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().background(Blue).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().size(64.dp, 44.dp).padding(6.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().size(64.dp, 44.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().size(64.dp, 44.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().size(64.dp, 44.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().size(64.dp, 44.dp).clipToBounds()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().offset(7.dp, 5.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().offset(7.dp, 5.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().offset(7.dp, 5.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().offset(7.dp, 5.dp).size(64.dp, 44.dp)) }
        }
    }
}

@Composable
private fun chains3_09() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().offset(7.dp, 5.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().clipToBounds().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().clipToBounds().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().clipToBounds().background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().clipToBounds().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.fillMaxWidth().clipToBounds().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).padding(6.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).padding(6.dp).background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).padding(6.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).padding(6.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).padding(6.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Red).padding(6.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Red).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Red).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Red).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Red).clipToBounds()) }
        }
    }
}

@Composable
private fun chains3_10() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Blue).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Blue).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Blue).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Blue).fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).background(Blue).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).size(64.dp, 44.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).size(64.dp, 44.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).size(64.dp, 44.dp).background(Blue)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).size(64.dp, 44.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).size(64.dp, 44.dp).clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).fillMaxWidth().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).fillMaxWidth().background(Red)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).fillMaxWidth().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).fillMaxWidth().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).fillMaxWidth().clipToBounds()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).clipToBounds().padding(6.dp)) }
        }
    }
}

@Composable
private fun chains3_11() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).clipToBounds().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).clipToBounds().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).clipToBounds().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.offset(7.dp, 5.dp).clipToBounds().fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().padding(6.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().padding(6.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().padding(6.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().padding(6.dp).fillMaxWidth()) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().padding(6.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Red).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Red).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Red).size(64.dp, 44.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Red).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Red).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Blue).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Blue).background(Red)) }
        }
    }
}

@Composable
private fun chains3_12() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Blue).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Blue).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().background(Blue).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().size(64.dp, 44.dp).padding(6.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().size(64.dp, 44.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().size(64.dp, 44.dp).background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().size(64.dp, 44.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().size(64.dp, 44.dp).offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().fillMaxWidth().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().fillMaxWidth().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().fillMaxWidth().background(Blue)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().fillMaxWidth().size(64.dp, 44.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().fillMaxWidth().offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().offset(7.dp, 5.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().offset(7.dp, 5.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().offset(7.dp, 5.dp).background(Blue)) }
        }
    }
}

@Composable
private fun chains3_13() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().offset(7.dp, 5.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Probe(Modifier.clipToBounds().offset(7.dp, 5.dp).fillMaxWidth()) }
        }
    }
}

@Composable
private fun text2_00() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(6.dp).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(6.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(6.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(6.dp).width(52.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(6.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(6.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).background(Red)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp).offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.background(Red).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.background(Red).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.background(Red).size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.background(Red).width(52.dp)) }
        }
    }
}

@Composable
private fun text2_01() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.background(Red).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.background(Red).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.size(64.dp, 44.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.size(64.dp, 44.dp).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.size(64.dp, 44.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.size(64.dp, 44.dp).width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.size(64.dp, 44.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.size(64.dp, 44.dp).offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.width(52.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.width(52.dp).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.width(52.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.width(52.dp).size(64.dp, 44.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.width(52.dp).fillMaxWidth()) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.width(52.dp).offset(7.dp, 5.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.fillMaxWidth().padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.fillMaxWidth().padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
        }
    }
}

@Composable
private fun text2_02() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.fillMaxWidth().background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.fillMaxWidth().size(64.dp, 44.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.fillMaxWidth().width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.fillMaxWidth().offset(7.dp, 5.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.offset(7.dp, 5.dp).padding(6.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.offset(7.dp, 5.dp).padding(start = 10.dp, top = 2.dp, end = 4.dp, bottom = 8.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.offset(7.dp, 5.dp).background(Red)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.offset(7.dp, 5.dp).size(64.dp, 44.dp)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.offset(7.dp, 5.dp).width(52.dp)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { Text("Ag Text", Modifier.offset(7.dp, 5.dp).fillMaxWidth()) }
        }
    }
}

@Composable
private fun rows_00() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.Start, Alignment.Top) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.Start, Alignment.CenterVertically) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.Start, Alignment.Bottom) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.End, Alignment.Top) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.End, Alignment.CenterVertically) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.End, Alignment.Bottom) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.Center, Alignment.Top) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.Center, Alignment.CenterVertically) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.Center, Alignment.Bottom) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceBetween, Alignment.Top) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceBetween, Alignment.CenterVertically) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceBetween, Alignment.Bottom) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceAround, Alignment.Top) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceAround, Alignment.CenterVertically) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceAround, Alignment.Bottom) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceEvenly, Alignment.Top) }
        }
    }
}

@Composable
private fun rows_01() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceEvenly, Alignment.CenterVertically) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.SpaceEvenly, Alignment.Bottom) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.spacedBy(7.dp), Alignment.Top) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.spacedBy(7.dp), Alignment.CenterVertically) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { RowProbe(Arrangement.spacedBy(7.dp), Alignment.Bottom) }
        }
    }
}

@Composable
private fun columns_00() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Top, Alignment.Start) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Top, Alignment.CenterHorizontally) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Top, Alignment.End) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Bottom, Alignment.Start) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Bottom, Alignment.CenterHorizontally) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Bottom, Alignment.End) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Center, Alignment.Start) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Center, Alignment.CenterHorizontally) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.Center, Alignment.End) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceBetween, Alignment.Start) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceBetween, Alignment.CenterHorizontally) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceBetween, Alignment.End) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceAround, Alignment.Start) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceAround, Alignment.CenterHorizontally) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceAround, Alignment.End) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceEvenly, Alignment.Start) }
        }
    }
}

@Composable
private fun columns_01() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceEvenly, Alignment.CenterHorizontally) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.SpaceEvenly, Alignment.End) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.spacedBy(7.dp), Alignment.Start) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.spacedBy(7.dp), Alignment.CenterHorizontally) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { ColumnProbe(Arrangement.spacedBy(7.dp), Alignment.End) }
        }
    }
}

@Composable
private fun boxes_00() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.TopStart) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.TopCenter) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.TopEnd) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.CenterStart) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.Center) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.CenterEnd) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.BottomStart) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.BottomCenter) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { BoxProbe(Alignment.BottomEnd) }
        }
    }
}

@Composable
private fun weights_00() {
    Column(Modifier.padding(4.dp)) {
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { WeightsProbe(listOf(1.0f to true, 1.0f to true)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { WeightsProbe(listOf(1.0f to true, 2.0f to true)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { WeightsProbe(listOf(1.0f to true, 0.0f to true, 1.0f to true)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { WeightsProbe(listOf(1.0f to false, 1.0f to true)) }
        }
        Row {
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { WeightsProbe(listOf(1.0f to true, 1.0f to true, 1.0f to true)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { WeightsProbe(listOf(0.0f to true, 3.0f to true, 0.0f to true)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { WeightsProbe(listOf(1.0f to false, 2.0f to false)) }
            Box(Modifier.size(128.dp, 102.dp).clipToBounds()) { WeightsProbe(listOf(1.0f to true, 1.0f to true, 1.0f to true, 1.0f to true, 1.0f to true, 1.0f to true, 1.0f to true)) }
        }
    }
}
