//! Generated by `tools/compose-twin/generate_matrix.py` from
//! `tools/compose-twin/matrix.toml`. Do not edit: change the description and
//! generate again.
//!
//! The Cranpose half of the modifier matrix (issue #905): each frame
//! is a grid of cells, one probe each, compared cell by cell with the
//! Compose frame in `tools/compose-twin/reference`.

use cranpose_ui::{
    composable, Alignment, BoxSpec, Color, Column, ColumnSpec, GraphicsLayer, HorizontalAlignment,
    LinearArrangement, Modifier, Row, RowSpec, Text, TextStyle, VerticalAlignment,
};

use super::compose_twin::{TwinGrid, TwinScene, TwinTolerance};

const RED: Color = Color(0.85, 0.35, 0.3, 1.0);
const BLUE: Color = Color(0.3, 0.55, 0.9, 1.0);
const GREEN: Color = Color(0.35, 0.8, 0.45, 1.0);
const GOLD: Color = Color(0.95, 0.75, 0.25, 1.0);
const DIM: Color = Color(0.22, 0.24, 0.3, 1.0);
const BLOCK_COLORS: [Color; 4] = [RED, BLUE, GOLD, GREEN];

/// Where every matrix frame lays its cells.
pub const MATRIX_GRID: TwinGrid = TwinGrid {
    origin: 4,
    columns: 4,
    cell_width: 128,
    cell_height: 102,
};

/// Every matrix frame, in the order the Compose twin renders them.
pub const MATRIX_FRAMES: [TwinScene; 55] = [
    TwinScene {
        name: "matrix-chains2-00",
        content: chains2_00,
        cells: CHAINS2_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains2-00@2.625",
        content: chains2_00,
        cells: CHAINS2_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains2-01",
        content: chains2_01,
        cells: CHAINS2_01_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains2-01@2.625",
        content: chains2_01,
        cells: CHAINS2_01_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains2-02",
        content: chains2_02,
        cells: CHAINS2_02_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains2-02@2.625",
        content: chains2_02,
        cells: CHAINS2_02_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains2-03",
        content: chains2_03,
        cells: CHAINS2_03_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains2-03@2.625",
        content: chains2_03,
        cells: CHAINS2_03_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains2-04",
        content: chains2_04,
        cells: CHAINS2_04_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains2-04@2.625",
        content: chains2_04,
        cells: CHAINS2_04_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains2-05",
        content: chains2_05,
        cells: CHAINS2_05_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains2-05@2.625",
        content: chains2_05,
        cells: CHAINS2_05_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-00",
        content: chains3_00,
        cells: CHAINS3_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-00@2.625",
        content: chains3_00,
        cells: CHAINS3_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-01",
        content: chains3_01,
        cells: CHAINS3_01_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-01@2.625",
        content: chains3_01,
        cells: CHAINS3_01_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-02",
        content: chains3_02,
        cells: CHAINS3_02_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-02@2.625",
        content: chains3_02,
        cells: CHAINS3_02_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-03",
        content: chains3_03,
        cells: CHAINS3_03_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-03@2.625",
        content: chains3_03,
        cells: CHAINS3_03_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-04",
        content: chains3_04,
        cells: CHAINS3_04_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-04@2.625",
        content: chains3_04,
        cells: CHAINS3_04_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-05",
        content: chains3_05,
        cells: CHAINS3_05_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-05@2.625",
        content: chains3_05,
        cells: CHAINS3_05_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-06",
        content: chains3_06,
        cells: CHAINS3_06_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-06@2.625",
        content: chains3_06,
        cells: CHAINS3_06_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-07",
        content: chains3_07,
        cells: CHAINS3_07_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-07@2.625",
        content: chains3_07,
        cells: CHAINS3_07_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-08",
        content: chains3_08,
        cells: CHAINS3_08_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-08@2.625",
        content: chains3_08,
        cells: CHAINS3_08_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-09",
        content: chains3_09,
        cells: CHAINS3_09_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-09@2.625",
        content: chains3_09,
        cells: CHAINS3_09_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-10",
        content: chains3_10,
        cells: CHAINS3_10_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-10@2.625",
        content: chains3_10,
        cells: CHAINS3_10_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-11",
        content: chains3_11,
        cells: CHAINS3_11_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-11@2.625",
        content: chains3_11,
        cells: CHAINS3_11_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-12",
        content: chains3_12,
        cells: CHAINS3_12_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-12@2.625",
        content: chains3_12,
        cells: CHAINS3_12_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-chains3-13",
        content: chains3_13,
        cells: CHAINS3_13_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-chains3-13@2.625",
        content: chains3_13,
        cells: CHAINS3_13_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-text2-00",
        content: text2_00,
        cells: TEXT2_00_CELLS,
        tolerance: TwinTolerance::Edges,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-text2-01",
        content: text2_01,
        cells: TEXT2_01_CELLS,
        tolerance: TwinTolerance::Edges,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-text2-02",
        content: text2_02,
        cells: TEXT2_02_CELLS,
        tolerance: TwinTolerance::Edges,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-rows-00",
        content: rows_00,
        cells: ROWS_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-rows-00@2.625",
        content: rows_00,
        cells: ROWS_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-rows-01",
        content: rows_01,
        cells: ROWS_01_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-rows-01@2.625",
        content: rows_01,
        cells: ROWS_01_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-columns-00",
        content: columns_00,
        cells: COLUMNS_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-columns-00@2.625",
        content: columns_00,
        cells: COLUMNS_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-columns-01",
        content: columns_01,
        cells: COLUMNS_01_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-columns-01@2.625",
        content: columns_01,
        cells: COLUMNS_01_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-boxes-00",
        content: boxes_00,
        cells: BOXES_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-boxes-00@2.625",
        content: boxes_00,
        cells: BOXES_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
    TwinScene {
        name: "matrix-weights-00",
        content: weights_00,
        cells: WEIGHTS_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 1.0,
    },
    TwinScene {
        name: "matrix-weights-00@2.625",
        content: weights_00,
        cells: WEIGHTS_00_CELLS,
        tolerance: TwinTolerance::Exact,
        density: 2.625,
    },
];

const CHAINS2_00_CELLS: &[&str] = &[
    "pad edge",
    "pad bg",
    "pad bg2",
    "pad size",
    "pad width",
    "pad fill",
    "pad offset",
    "pad clip",
    "pad alpha",
    "edge pad",
    "edge bg",
    "edge bg2",
    "edge size",
    "edge width",
    "edge fill",
    "edge offset",
];

const CHAINS2_01_CELLS: &[&str] = &[
    "edge clip",
    "edge alpha",
    "bg pad",
    "bg edge",
    "bg bg2",
    "bg size",
    "bg width",
    "bg fill",
    "bg offset",
    "bg clip",
    "bg alpha",
    "bg2 pad",
    "bg2 edge",
    "bg2 bg",
    "bg2 size",
    "bg2 width",
];

const CHAINS2_02_CELLS: &[&str] = &[
    "bg2 fill",
    "bg2 offset",
    "bg2 clip",
    "bg2 alpha",
    "size pad",
    "size edge",
    "size bg",
    "size bg2",
    "size width",
    "size fill",
    "size offset",
    "size clip",
    "size alpha",
    "width pad",
    "width edge",
    "width bg",
];

const CHAINS2_03_CELLS: &[&str] = &[
    "width bg2",
    "width size",
    "width fill",
    "width offset",
    "width clip",
    "width alpha",
    "fill pad",
    "fill edge",
    "fill bg",
    "fill bg2",
    "fill size",
    "fill width",
    "fill offset",
    "fill clip",
    "fill alpha",
    "offset pad",
];

const CHAINS2_04_CELLS: &[&str] = &[
    "offset edge",
    "offset bg",
    "offset bg2",
    "offset size",
    "offset width",
    "offset fill",
    "offset clip",
    "offset alpha",
    "clip pad",
    "clip edge",
    "clip bg",
    "clip bg2",
    "clip size",
    "clip width",
    "clip fill",
    "clip offset",
];

const CHAINS2_05_CELLS: &[&str] = &[
    "clip alpha",
    "alpha pad",
    "alpha edge",
    "alpha bg",
    "alpha bg2",
    "alpha size",
    "alpha width",
    "alpha fill",
    "alpha offset",
    "alpha clip",
];

const CHAINS3_00_CELLS: &[&str] = &[
    "pad bg bg2",
    "pad bg size",
    "pad bg fill",
    "pad bg offset",
    "pad bg clip",
    "pad bg2 bg",
    "pad bg2 size",
    "pad bg2 fill",
    "pad bg2 offset",
    "pad bg2 clip",
    "pad size bg",
    "pad size bg2",
    "pad size fill",
    "pad size offset",
    "pad size clip",
    "pad fill bg",
];

const CHAINS3_01_CELLS: &[&str] = &[
    "pad fill bg2",
    "pad fill size",
    "pad fill offset",
    "pad fill clip",
    "pad offset bg",
    "pad offset bg2",
    "pad offset size",
    "pad offset fill",
    "pad offset clip",
    "pad clip bg",
    "pad clip bg2",
    "pad clip size",
    "pad clip fill",
    "pad clip offset",
    "bg pad bg2",
    "bg pad size",
];

const CHAINS3_02_CELLS: &[&str] = &[
    "bg pad fill",
    "bg pad offset",
    "bg pad clip",
    "bg bg2 pad",
    "bg bg2 size",
    "bg bg2 fill",
    "bg bg2 offset",
    "bg bg2 clip",
    "bg size pad",
    "bg size bg2",
    "bg size fill",
    "bg size offset",
    "bg size clip",
    "bg fill pad",
    "bg fill bg2",
    "bg fill size",
];

const CHAINS3_03_CELLS: &[&str] = &[
    "bg fill offset",
    "bg fill clip",
    "bg offset pad",
    "bg offset bg2",
    "bg offset size",
    "bg offset fill",
    "bg offset clip",
    "bg clip pad",
    "bg clip bg2",
    "bg clip size",
    "bg clip fill",
    "bg clip offset",
    "bg2 pad bg",
    "bg2 pad size",
    "bg2 pad fill",
    "bg2 pad offset",
];

const CHAINS3_04_CELLS: &[&str] = &[
    "bg2 pad clip",
    "bg2 bg pad",
    "bg2 bg size",
    "bg2 bg fill",
    "bg2 bg offset",
    "bg2 bg clip",
    "bg2 size pad",
    "bg2 size bg",
    "bg2 size fill",
    "bg2 size offset",
    "bg2 size clip",
    "bg2 fill pad",
    "bg2 fill bg",
    "bg2 fill size",
    "bg2 fill offset",
    "bg2 fill clip",
];

const CHAINS3_05_CELLS: &[&str] = &[
    "bg2 offset pad",
    "bg2 offset bg",
    "bg2 offset size",
    "bg2 offset fill",
    "bg2 offset clip",
    "bg2 clip pad",
    "bg2 clip bg",
    "bg2 clip size",
    "bg2 clip fill",
    "bg2 clip offset",
    "size pad bg",
    "size pad bg2",
    "size pad fill",
    "size pad offset",
    "size pad clip",
    "size bg pad",
];

const CHAINS3_06_CELLS: &[&str] = &[
    "size bg bg2",
    "size bg fill",
    "size bg offset",
    "size bg clip",
    "size bg2 pad",
    "size bg2 bg",
    "size bg2 fill",
    "size bg2 offset",
    "size bg2 clip",
    "size fill pad",
    "size fill bg",
    "size fill bg2",
    "size fill offset",
    "size fill clip",
    "size offset pad",
    "size offset bg",
];

const CHAINS3_07_CELLS: &[&str] = &[
    "size offset bg2",
    "size offset fill",
    "size offset clip",
    "size clip pad",
    "size clip bg",
    "size clip bg2",
    "size clip fill",
    "size clip offset",
    "fill pad bg",
    "fill pad bg2",
    "fill pad size",
    "fill pad offset",
    "fill pad clip",
    "fill bg pad",
    "fill bg bg2",
    "fill bg size",
];

const CHAINS3_08_CELLS: &[&str] = &[
    "fill bg offset",
    "fill bg clip",
    "fill bg2 pad",
    "fill bg2 bg",
    "fill bg2 size",
    "fill bg2 offset",
    "fill bg2 clip",
    "fill size pad",
    "fill size bg",
    "fill size bg2",
    "fill size offset",
    "fill size clip",
    "fill offset pad",
    "fill offset bg",
    "fill offset bg2",
    "fill offset size",
];

const CHAINS3_09_CELLS: &[&str] = &[
    "fill offset clip",
    "fill clip pad",
    "fill clip bg",
    "fill clip bg2",
    "fill clip size",
    "fill clip offset",
    "offset pad bg",
    "offset pad bg2",
    "offset pad size",
    "offset pad fill",
    "offset pad clip",
    "offset bg pad",
    "offset bg bg2",
    "offset bg size",
    "offset bg fill",
    "offset bg clip",
];

const CHAINS3_10_CELLS: &[&str] = &[
    "offset bg2 pad",
    "offset bg2 bg",
    "offset bg2 size",
    "offset bg2 fill",
    "offset bg2 clip",
    "offset size pad",
    "offset size bg",
    "offset size bg2",
    "offset size fill",
    "offset size clip",
    "offset fill pad",
    "offset fill bg",
    "offset fill bg2",
    "offset fill size",
    "offset fill clip",
    "offset clip pad",
];

const CHAINS3_11_CELLS: &[&str] = &[
    "offset clip bg",
    "offset clip bg2",
    "offset clip size",
    "offset clip fill",
    "clip pad bg",
    "clip pad bg2",
    "clip pad size",
    "clip pad fill",
    "clip pad offset",
    "clip bg pad",
    "clip bg bg2",
    "clip bg size",
    "clip bg fill",
    "clip bg offset",
    "clip bg2 pad",
    "clip bg2 bg",
];

const CHAINS3_12_CELLS: &[&str] = &[
    "clip bg2 size",
    "clip bg2 fill",
    "clip bg2 offset",
    "clip size pad",
    "clip size bg",
    "clip size bg2",
    "clip size fill",
    "clip size offset",
    "clip fill pad",
    "clip fill bg",
    "clip fill bg2",
    "clip fill size",
    "clip fill offset",
    "clip offset pad",
    "clip offset bg",
    "clip offset bg2",
];

const CHAINS3_13_CELLS: &[&str] = &["clip offset size", "clip offset fill"];

const TEXT2_00_CELLS: &[&str] = &[
    "pad edge",
    "pad bg",
    "pad size",
    "pad width",
    "pad fill",
    "pad offset",
    "edge pad",
    "edge bg",
    "edge size",
    "edge width",
    "edge fill",
    "edge offset",
    "bg pad",
    "bg edge",
    "bg size",
    "bg width",
];

const TEXT2_01_CELLS: &[&str] = &[
    "bg fill",
    "bg offset",
    "size pad",
    "size edge",
    "size bg",
    "size width",
    "size fill",
    "size offset",
    "width pad",
    "width edge",
    "width bg",
    "width size",
    "width fill",
    "width offset",
    "fill pad",
    "fill edge",
];

const TEXT2_02_CELLS: &[&str] = &[
    "fill bg",
    "fill size",
    "fill width",
    "fill offset",
    "offset pad",
    "offset edge",
    "offset bg",
    "offset size",
    "offset width",
    "offset fill",
];

const ROWS_00_CELLS: &[&str] = &[
    "row start top",
    "row start center",
    "row start bottom",
    "row end top",
    "row end center",
    "row end bottom",
    "row center top",
    "row center center",
    "row center bottom",
    "row between top",
    "row between center",
    "row between bottom",
    "row around top",
    "row around center",
    "row around bottom",
    "row evenly top",
];

const ROWS_01_CELLS: &[&str] = &[
    "row evenly center",
    "row evenly bottom",
    "row spaced top",
    "row spaced center",
    "row spaced bottom",
];

const COLUMNS_00_CELLS: &[&str] = &[
    "column start start",
    "column start center",
    "column start end",
    "column end start",
    "column end center",
    "column end end",
    "column center start",
    "column center center",
    "column center end",
    "column between start",
    "column between center",
    "column between end",
    "column around start",
    "column around center",
    "column around end",
    "column evenly start",
];

const COLUMNS_01_CELLS: &[&str] = &[
    "column evenly center",
    "column evenly end",
    "column spaced start",
    "column spaced center",
    "column spaced end",
];

const BOXES_00_CELLS: &[&str] = &[
    "box top_start",
    "box top_center",
    "box top_end",
    "box center_start",
    "box center",
    "box center_end",
    "box bottom_start",
    "box bottom_center",
    "box bottom_end",
];

const WEIGHTS_00_CELLS: &[&str] = &[
    "weights 0",
    "weights 1",
    "weights 2",
    "weights 3",
    "weights 4",
    "weights 5",
    "weights 6",
    "weights 7",
];

/// The block every chain probe wraps.
#[composable]
fn probe(modifier: Modifier) {
    cranpose_ui::Box(modifier, BoxSpec::default(), || {
        block(20.0, 14.0, GREEN);
    });
}

#[composable]
fn block(width: f32, height: f32, color: Color) {
    cranpose_ui::Box(
        Modifier::empty()
            .size_points(width, height)
            .background(color),
        BoxSpec::default(),
        || {},
    );
}

/// Three blocks in a dim row, arranged and aligned as given.
#[composable]
fn row_probe(arrangement: LinearArrangement, alignment: VerticalAlignment) {
    Row(
        Modifier::empty().size_points(121.0, 65.0).background(DIM),
        RowSpec::new()
            .horizontal_arrangement(arrangement)
            .vertical_alignment(alignment),
        || {
            block(16.0, 12.0, RED);
            block(22.0, 30.0, BLUE);
            block(12.0, 20.0, GOLD);
        },
    );
}

/// The same blocks, turned, in a dim column.
#[composable]
fn column_probe(arrangement: LinearArrangement, alignment: HorizontalAlignment) {
    Column(
        Modifier::empty().size_points(89.0, 97.0).background(DIM),
        ColumnSpec::new()
            .vertical_arrangement(arrangement)
            .horizontal_alignment(alignment),
        || {
            block(12.0, 16.0, RED);
            block(30.0, 22.0, BLUE);
            block(20.0, 12.0, GOLD);
        },
    );
}

/// A block in a dim box at `alignment`.
#[composable]
fn box_probe(alignment: Alignment) {
    cranpose_ui::Box(
        Modifier::empty().size_points(121.0, 91.0).background(DIM),
        BoxSpec::default().content_alignment(alignment),
        || block(30.0, 20.0, RED),
    );
}

/// A dim row of `(weight, fill)` children; weight 0 is a fixed block.
#[composable]
fn weights_probe(children: &'static [(f32, bool)]) {
    Row(
        Modifier::empty().size_points(121.0, 40.0).background(DIM),
        RowSpec::new(),
        move || {
            for (at, &(weight, fill)) in children.iter().enumerate() {
                let color = BLOCK_COLORS[at % BLOCK_COLORS.len()];
                cranpose_core::with_key(&at, || {
                    if weight == 0.0 {
                        block(18.0, 24.0, color);
                    } else {
                        cranpose_ui::Box(
                            Modifier::empty()
                                .weight_with_fill(weight, fill)
                                .width(10.0)
                                .height(24.0)
                                .background(color),
                            BoxSpec::default(),
                            || {},
                        );
                    }
                });
            }
        },
    );
}

/// Lays `cells` out on [`MATRIX_GRID`], each in its own clipped cell.
#[composable]
fn grid(cells: &'static [fn()]) {
    Column(
        Modifier::empty().padding(4.0),
        ColumnSpec::new(),
        move || {
            for (row_index, row) in cells.chunks(4).enumerate() {
                cranpose_core::with_key(&row_index, || {
                    Row(Modifier::empty(), RowSpec::new(), move || {
                        for (index, cell) in row.iter().enumerate() {
                            cranpose_core::with_key(&index, || {
                                cranpose_ui::Box(
                                    Modifier::empty().size_points(128.0, 102.0).clip_to_bounds(),
                                    BoxSpec::default(),
                                    move || cell(),
                                );
                            });
                        }
                    });
                });
            }
        },
    );
}

#[composable]
fn chains2_00() {
    grid(&[
        chains2_00_00,
        chains2_00_01,
        chains2_00_02,
        chains2_00_03,
        chains2_00_04,
        chains2_00_05,
        chains2_00_06,
        chains2_00_07,
        chains2_00_08,
        chains2_00_09,
        chains2_00_10,
        chains2_00_11,
        chains2_00_12,
        chains2_00_13,
        chains2_00_14,
        chains2_00_15,
    ]);
}

#[composable]
fn chains2_00_00() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_00_01() {
    probe(Modifier::empty().padding(6.0).background(RED));
}

#[composable]
fn chains2_00_02() {
    probe(Modifier::empty().padding(6.0).background(BLUE));
}

#[composable]
fn chains2_00_03() {
    probe(Modifier::empty().padding(6.0).size_points(64.0, 44.0));
}

#[composable]
fn chains2_00_04() {
    probe(Modifier::empty().padding(6.0).width(52.0));
}

#[composable]
fn chains2_00_05() {
    probe(Modifier::empty().padding(6.0).fill_max_width());
}

#[composable]
fn chains2_00_06() {
    probe(Modifier::empty().padding(6.0).offset(7.0, 5.0));
}

#[composable]
fn chains2_00_07() {
    probe(Modifier::empty().padding(6.0).clip_to_bounds());
}

#[composable]
fn chains2_00_08() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_00_09() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .padding(6.0),
    );
}

#[composable]
fn chains2_00_10() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .background(RED),
    );
}

#[composable]
fn chains2_00_11() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .background(BLUE),
    );
}

#[composable]
fn chains2_00_12() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains2_00_13() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .width(52.0),
    );
}

#[composable]
fn chains2_00_14() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains2_00_15() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains2_01() {
    grid(&[
        chains2_01_00,
        chains2_01_01,
        chains2_01_02,
        chains2_01_03,
        chains2_01_04,
        chains2_01_05,
        chains2_01_06,
        chains2_01_07,
        chains2_01_08,
        chains2_01_09,
        chains2_01_10,
        chains2_01_11,
        chains2_01_12,
        chains2_01_13,
        chains2_01_14,
        chains2_01_15,
    ]);
}

#[composable]
fn chains2_01_00() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains2_01_01() {
    probe(
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_01_02() {
    probe(Modifier::empty().background(RED).padding(6.0));
}

#[composable]
fn chains2_01_03() {
    probe(
        Modifier::empty()
            .background(RED)
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_01_04() {
    probe(Modifier::empty().background(RED).background(BLUE));
}

#[composable]
fn chains2_01_05() {
    probe(Modifier::empty().background(RED).size_points(64.0, 44.0));
}

#[composable]
fn chains2_01_06() {
    probe(Modifier::empty().background(RED).width(52.0));
}

#[composable]
fn chains2_01_07() {
    probe(Modifier::empty().background(RED).fill_max_width());
}

#[composable]
fn chains2_01_08() {
    probe(Modifier::empty().background(RED).offset(7.0, 5.0));
}

#[composable]
fn chains2_01_09() {
    probe(Modifier::empty().background(RED).clip_to_bounds());
}

#[composable]
fn chains2_01_10() {
    probe(
        Modifier::empty()
            .background(RED)
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_01_11() {
    probe(Modifier::empty().background(BLUE).padding(6.0));
}

#[composable]
fn chains2_01_12() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_01_13() {
    probe(Modifier::empty().background(BLUE).background(RED));
}

#[composable]
fn chains2_01_14() {
    probe(Modifier::empty().background(BLUE).size_points(64.0, 44.0));
}

#[composable]
fn chains2_01_15() {
    probe(Modifier::empty().background(BLUE).width(52.0));
}

#[composable]
fn chains2_02() {
    grid(&[
        chains2_02_00,
        chains2_02_01,
        chains2_02_02,
        chains2_02_03,
        chains2_02_04,
        chains2_02_05,
        chains2_02_06,
        chains2_02_07,
        chains2_02_08,
        chains2_02_09,
        chains2_02_10,
        chains2_02_11,
        chains2_02_12,
        chains2_02_13,
        chains2_02_14,
        chains2_02_15,
    ]);
}

#[composable]
fn chains2_02_00() {
    probe(Modifier::empty().background(BLUE).fill_max_width());
}

#[composable]
fn chains2_02_01() {
    probe(Modifier::empty().background(BLUE).offset(7.0, 5.0));
}

#[composable]
fn chains2_02_02() {
    probe(Modifier::empty().background(BLUE).clip_to_bounds());
}

#[composable]
fn chains2_02_03() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_02_04() {
    probe(Modifier::empty().size_points(64.0, 44.0).padding(6.0));
}

#[composable]
fn chains2_02_05() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_02_06() {
    probe(Modifier::empty().size_points(64.0, 44.0).background(RED));
}

#[composable]
fn chains2_02_07() {
    probe(Modifier::empty().size_points(64.0, 44.0).background(BLUE));
}

#[composable]
fn chains2_02_08() {
    probe(Modifier::empty().size_points(64.0, 44.0).width(52.0));
}

#[composable]
fn chains2_02_09() {
    probe(Modifier::empty().size_points(64.0, 44.0).fill_max_width());
}

#[composable]
fn chains2_02_10() {
    probe(Modifier::empty().size_points(64.0, 44.0).offset(7.0, 5.0));
}

#[composable]
fn chains2_02_11() {
    probe(Modifier::empty().size_points(64.0, 44.0).clip_to_bounds());
}

#[composable]
fn chains2_02_12() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_02_13() {
    probe(Modifier::empty().width(52.0).padding(6.0));
}

#[composable]
fn chains2_02_14() {
    probe(
        Modifier::empty()
            .width(52.0)
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_02_15() {
    probe(Modifier::empty().width(52.0).background(RED));
}

#[composable]
fn chains2_03() {
    grid(&[
        chains2_03_00,
        chains2_03_01,
        chains2_03_02,
        chains2_03_03,
        chains2_03_04,
        chains2_03_05,
        chains2_03_06,
        chains2_03_07,
        chains2_03_08,
        chains2_03_09,
        chains2_03_10,
        chains2_03_11,
        chains2_03_12,
        chains2_03_13,
        chains2_03_14,
        chains2_03_15,
    ]);
}

#[composable]
fn chains2_03_00() {
    probe(Modifier::empty().width(52.0).background(BLUE));
}

#[composable]
fn chains2_03_01() {
    probe(Modifier::empty().width(52.0).size_points(64.0, 44.0));
}

#[composable]
fn chains2_03_02() {
    probe(Modifier::empty().width(52.0).fill_max_width());
}

#[composable]
fn chains2_03_03() {
    probe(Modifier::empty().width(52.0).offset(7.0, 5.0));
}

#[composable]
fn chains2_03_04() {
    probe(Modifier::empty().width(52.0).clip_to_bounds());
}

#[composable]
fn chains2_03_05() {
    probe(
        Modifier::empty()
            .width(52.0)
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_03_06() {
    probe(Modifier::empty().fill_max_width().padding(6.0));
}

#[composable]
fn chains2_03_07() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_03_08() {
    probe(Modifier::empty().fill_max_width().background(RED));
}

#[composable]
fn chains2_03_09() {
    probe(Modifier::empty().fill_max_width().background(BLUE));
}

#[composable]
fn chains2_03_10() {
    probe(Modifier::empty().fill_max_width().size_points(64.0, 44.0));
}

#[composable]
fn chains2_03_11() {
    probe(Modifier::empty().fill_max_width().width(52.0));
}

#[composable]
fn chains2_03_12() {
    probe(Modifier::empty().fill_max_width().offset(7.0, 5.0));
}

#[composable]
fn chains2_03_13() {
    probe(Modifier::empty().fill_max_width().clip_to_bounds());
}

#[composable]
fn chains2_03_14() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_03_15() {
    probe(Modifier::empty().offset(7.0, 5.0).padding(6.0));
}

#[composable]
fn chains2_04() {
    grid(&[
        chains2_04_00,
        chains2_04_01,
        chains2_04_02,
        chains2_04_03,
        chains2_04_04,
        chains2_04_05,
        chains2_04_06,
        chains2_04_07,
        chains2_04_08,
        chains2_04_09,
        chains2_04_10,
        chains2_04_11,
        chains2_04_12,
        chains2_04_13,
        chains2_04_14,
        chains2_04_15,
    ]);
}

#[composable]
fn chains2_04_00() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_04_01() {
    probe(Modifier::empty().offset(7.0, 5.0).background(RED));
}

#[composable]
fn chains2_04_02() {
    probe(Modifier::empty().offset(7.0, 5.0).background(BLUE));
}

#[composable]
fn chains2_04_03() {
    probe(Modifier::empty().offset(7.0, 5.0).size_points(64.0, 44.0));
}

#[composable]
fn chains2_04_04() {
    probe(Modifier::empty().offset(7.0, 5.0).width(52.0));
}

#[composable]
fn chains2_04_05() {
    probe(Modifier::empty().offset(7.0, 5.0).fill_max_width());
}

#[composable]
fn chains2_04_06() {
    probe(Modifier::empty().offset(7.0, 5.0).clip_to_bounds());
}

#[composable]
fn chains2_04_07() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_04_08() {
    probe(Modifier::empty().clip_to_bounds().padding(6.0));
}

#[composable]
fn chains2_04_09() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_04_10() {
    probe(Modifier::empty().clip_to_bounds().background(RED));
}

#[composable]
fn chains2_04_11() {
    probe(Modifier::empty().clip_to_bounds().background(BLUE));
}

#[composable]
fn chains2_04_12() {
    probe(Modifier::empty().clip_to_bounds().size_points(64.0, 44.0));
}

#[composable]
fn chains2_04_13() {
    probe(Modifier::empty().clip_to_bounds().width(52.0));
}

#[composable]
fn chains2_04_14() {
    probe(Modifier::empty().clip_to_bounds().fill_max_width());
}

#[composable]
fn chains2_04_15() {
    probe(Modifier::empty().clip_to_bounds().offset(7.0, 5.0));
}

#[composable]
fn chains2_05() {
    grid(&[
        chains2_05_00,
        chains2_05_01,
        chains2_05_02,
        chains2_05_03,
        chains2_05_04,
        chains2_05_05,
        chains2_05_06,
        chains2_05_07,
        chains2_05_08,
        chains2_05_09,
    ]);
}

#[composable]
fn chains2_05_00() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            }),
    );
}

#[composable]
fn chains2_05_01() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .padding(6.0),
    );
}

#[composable]
fn chains2_05_02() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .padding_each(10.0, 2.0, 4.0, 8.0),
    );
}

#[composable]
fn chains2_05_03() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .background(RED),
    );
}

#[composable]
fn chains2_05_04() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .background(BLUE),
    );
}

#[composable]
fn chains2_05_05() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains2_05_06() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .width(52.0),
    );
}

#[composable]
fn chains2_05_07() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .fill_max_width(),
    );
}

#[composable]
fn chains2_05_08() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains2_05_09() {
    probe(
        Modifier::empty()
            .graphics_layer_value(GraphicsLayer {
                alpha: 0.5,
                ..Default::default()
            })
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_00() {
    grid(&[
        chains3_00_00,
        chains3_00_01,
        chains3_00_02,
        chains3_00_03,
        chains3_00_04,
        chains3_00_05,
        chains3_00_06,
        chains3_00_07,
        chains3_00_08,
        chains3_00_09,
        chains3_00_10,
        chains3_00_11,
        chains3_00_12,
        chains3_00_13,
        chains3_00_14,
        chains3_00_15,
    ]);
}

#[composable]
fn chains3_00_00() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(RED)
            .background(BLUE),
    );
}

#[composable]
fn chains3_00_01() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(RED)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_00_02() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(RED)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_00_03() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(RED)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_00_04() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(RED)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_00_05() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(BLUE)
            .background(RED),
    );
}

#[composable]
fn chains3_00_06() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(BLUE)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_00_07() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(BLUE)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_00_08() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(BLUE)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_00_09() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .background(BLUE)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_00_10() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .size_points(64.0, 44.0)
            .background(RED),
    );
}

#[composable]
fn chains3_00_11() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .size_points(64.0, 44.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_00_12() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .size_points(64.0, 44.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_00_13() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_00_14() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .size_points(64.0, 44.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_00_15() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .fill_max_width()
            .background(RED),
    );
}

#[composable]
fn chains3_01() {
    grid(&[
        chains3_01_00,
        chains3_01_01,
        chains3_01_02,
        chains3_01_03,
        chains3_01_04,
        chains3_01_05,
        chains3_01_06,
        chains3_01_07,
        chains3_01_08,
        chains3_01_09,
        chains3_01_10,
        chains3_01_11,
        chains3_01_12,
        chains3_01_13,
        chains3_01_14,
        chains3_01_15,
    ]);
}

#[composable]
fn chains3_01_00() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .fill_max_width()
            .background(BLUE),
    );
}

#[composable]
fn chains3_01_01() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .fill_max_width()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_01_02() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .fill_max_width()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_01_03() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .fill_max_width()
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_01_04() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .offset(7.0, 5.0)
            .background(RED),
    );
}

#[composable]
fn chains3_01_05() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .offset(7.0, 5.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_01_06() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_01_07() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .offset(7.0, 5.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_01_08() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .offset(7.0, 5.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_01_09() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .clip_to_bounds()
            .background(RED),
    );
}

#[composable]
fn chains3_01_10() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .clip_to_bounds()
            .background(BLUE),
    );
}

#[composable]
fn chains3_01_11() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .clip_to_bounds()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_01_12() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .clip_to_bounds()
            .fill_max_width(),
    );
}

#[composable]
fn chains3_01_13() {
    probe(
        Modifier::empty()
            .padding(6.0)
            .clip_to_bounds()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_01_14() {
    probe(
        Modifier::empty()
            .background(RED)
            .padding(6.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_01_15() {
    probe(
        Modifier::empty()
            .background(RED)
            .padding(6.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_02() {
    grid(&[
        chains3_02_00,
        chains3_02_01,
        chains3_02_02,
        chains3_02_03,
        chains3_02_04,
        chains3_02_05,
        chains3_02_06,
        chains3_02_07,
        chains3_02_08,
        chains3_02_09,
        chains3_02_10,
        chains3_02_11,
        chains3_02_12,
        chains3_02_13,
        chains3_02_14,
        chains3_02_15,
    ]);
}

#[composable]
fn chains3_02_00() {
    probe(
        Modifier::empty()
            .background(RED)
            .padding(6.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_02_01() {
    probe(
        Modifier::empty()
            .background(RED)
            .padding(6.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_02_02() {
    probe(
        Modifier::empty()
            .background(RED)
            .padding(6.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_02_03() {
    probe(
        Modifier::empty()
            .background(RED)
            .background(BLUE)
            .padding(6.0),
    );
}

#[composable]
fn chains3_02_04() {
    probe(
        Modifier::empty()
            .background(RED)
            .background(BLUE)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_02_05() {
    probe(
        Modifier::empty()
            .background(RED)
            .background(BLUE)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_02_06() {
    probe(
        Modifier::empty()
            .background(RED)
            .background(BLUE)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_02_07() {
    probe(
        Modifier::empty()
            .background(RED)
            .background(BLUE)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_02_08() {
    probe(
        Modifier::empty()
            .background(RED)
            .size_points(64.0, 44.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_02_09() {
    probe(
        Modifier::empty()
            .background(RED)
            .size_points(64.0, 44.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_02_10() {
    probe(
        Modifier::empty()
            .background(RED)
            .size_points(64.0, 44.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_02_11() {
    probe(
        Modifier::empty()
            .background(RED)
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_02_12() {
    probe(
        Modifier::empty()
            .background(RED)
            .size_points(64.0, 44.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_02_13() {
    probe(
        Modifier::empty()
            .background(RED)
            .fill_max_width()
            .padding(6.0),
    );
}

#[composable]
fn chains3_02_14() {
    probe(
        Modifier::empty()
            .background(RED)
            .fill_max_width()
            .background(BLUE),
    );
}

#[composable]
fn chains3_02_15() {
    probe(
        Modifier::empty()
            .background(RED)
            .fill_max_width()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_03() {
    grid(&[
        chains3_03_00,
        chains3_03_01,
        chains3_03_02,
        chains3_03_03,
        chains3_03_04,
        chains3_03_05,
        chains3_03_06,
        chains3_03_07,
        chains3_03_08,
        chains3_03_09,
        chains3_03_10,
        chains3_03_11,
        chains3_03_12,
        chains3_03_13,
        chains3_03_14,
        chains3_03_15,
    ]);
}

#[composable]
fn chains3_03_00() {
    probe(
        Modifier::empty()
            .background(RED)
            .fill_max_width()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_03_01() {
    probe(
        Modifier::empty()
            .background(RED)
            .fill_max_width()
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_03_02() {
    probe(
        Modifier::empty()
            .background(RED)
            .offset(7.0, 5.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_03_03() {
    probe(
        Modifier::empty()
            .background(RED)
            .offset(7.0, 5.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_03_04() {
    probe(
        Modifier::empty()
            .background(RED)
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_03_05() {
    probe(
        Modifier::empty()
            .background(RED)
            .offset(7.0, 5.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_03_06() {
    probe(
        Modifier::empty()
            .background(RED)
            .offset(7.0, 5.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_03_07() {
    probe(
        Modifier::empty()
            .background(RED)
            .clip_to_bounds()
            .padding(6.0),
    );
}

#[composable]
fn chains3_03_08() {
    probe(
        Modifier::empty()
            .background(RED)
            .clip_to_bounds()
            .background(BLUE),
    );
}

#[composable]
fn chains3_03_09() {
    probe(
        Modifier::empty()
            .background(RED)
            .clip_to_bounds()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_03_10() {
    probe(
        Modifier::empty()
            .background(RED)
            .clip_to_bounds()
            .fill_max_width(),
    );
}

#[composable]
fn chains3_03_11() {
    probe(
        Modifier::empty()
            .background(RED)
            .clip_to_bounds()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_03_12() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .padding(6.0)
            .background(RED),
    );
}

#[composable]
fn chains3_03_13() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .padding(6.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_03_14() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .padding(6.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_03_15() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .padding(6.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_04() {
    grid(&[
        chains3_04_00,
        chains3_04_01,
        chains3_04_02,
        chains3_04_03,
        chains3_04_04,
        chains3_04_05,
        chains3_04_06,
        chains3_04_07,
        chains3_04_08,
        chains3_04_09,
        chains3_04_10,
        chains3_04_11,
        chains3_04_12,
        chains3_04_13,
        chains3_04_14,
        chains3_04_15,
    ]);
}

#[composable]
fn chains3_04_00() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .padding(6.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_04_01() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .background(RED)
            .padding(6.0),
    );
}

#[composable]
fn chains3_04_02() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .background(RED)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_04_03() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .background(RED)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_04_04() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .background(RED)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_04_05() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .background(RED)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_04_06() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .size_points(64.0, 44.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_04_07() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .size_points(64.0, 44.0)
            .background(RED),
    );
}

#[composable]
fn chains3_04_08() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .size_points(64.0, 44.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_04_09() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_04_10() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .size_points(64.0, 44.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_04_11() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .fill_max_width()
            .padding(6.0),
    );
}

#[composable]
fn chains3_04_12() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .fill_max_width()
            .background(RED),
    );
}

#[composable]
fn chains3_04_13() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .fill_max_width()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_04_14() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .fill_max_width()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_04_15() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .fill_max_width()
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_05() {
    grid(&[
        chains3_05_00,
        chains3_05_01,
        chains3_05_02,
        chains3_05_03,
        chains3_05_04,
        chains3_05_05,
        chains3_05_06,
        chains3_05_07,
        chains3_05_08,
        chains3_05_09,
        chains3_05_10,
        chains3_05_11,
        chains3_05_12,
        chains3_05_13,
        chains3_05_14,
        chains3_05_15,
    ]);
}

#[composable]
fn chains3_05_00() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .offset(7.0, 5.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_05_01() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .offset(7.0, 5.0)
            .background(RED),
    );
}

#[composable]
fn chains3_05_02() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_05_03() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .offset(7.0, 5.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_05_04() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .offset(7.0, 5.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_05_05() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .clip_to_bounds()
            .padding(6.0),
    );
}

#[composable]
fn chains3_05_06() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .clip_to_bounds()
            .background(RED),
    );
}

#[composable]
fn chains3_05_07() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .clip_to_bounds()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_05_08() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .clip_to_bounds()
            .fill_max_width(),
    );
}

#[composable]
fn chains3_05_09() {
    probe(
        Modifier::empty()
            .background(BLUE)
            .clip_to_bounds()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_05_10() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .padding(6.0)
            .background(RED),
    );
}

#[composable]
fn chains3_05_11() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .padding(6.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_05_12() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .padding(6.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_05_13() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .padding(6.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_05_14() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .padding(6.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_05_15() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(RED)
            .padding(6.0),
    );
}

#[composable]
fn chains3_06() {
    grid(&[
        chains3_06_00,
        chains3_06_01,
        chains3_06_02,
        chains3_06_03,
        chains3_06_04,
        chains3_06_05,
        chains3_06_06,
        chains3_06_07,
        chains3_06_08,
        chains3_06_09,
        chains3_06_10,
        chains3_06_11,
        chains3_06_12,
        chains3_06_13,
        chains3_06_14,
        chains3_06_15,
    ]);
}

#[composable]
fn chains3_06_00() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(RED)
            .background(BLUE),
    );
}

#[composable]
fn chains3_06_01() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(RED)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_06_02() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(RED)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_06_03() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(RED)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_06_04() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(BLUE)
            .padding(6.0),
    );
}

#[composable]
fn chains3_06_05() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(BLUE)
            .background(RED),
    );
}

#[composable]
fn chains3_06_06() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(BLUE)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_06_07() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(BLUE)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_06_08() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .background(BLUE)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_06_09() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .fill_max_width()
            .padding(6.0),
    );
}

#[composable]
fn chains3_06_10() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .fill_max_width()
            .background(RED),
    );
}

#[composable]
fn chains3_06_11() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .fill_max_width()
            .background(BLUE),
    );
}

#[composable]
fn chains3_06_12() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .fill_max_width()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_06_13() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .fill_max_width()
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_06_14() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_06_15() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0)
            .background(RED),
    );
}

#[composable]
fn chains3_07() {
    grid(&[
        chains3_07_00,
        chains3_07_01,
        chains3_07_02,
        chains3_07_03,
        chains3_07_04,
        chains3_07_05,
        chains3_07_06,
        chains3_07_07,
        chains3_07_08,
        chains3_07_09,
        chains3_07_10,
        chains3_07_11,
        chains3_07_12,
        chains3_07_13,
        chains3_07_14,
        chains3_07_15,
    ]);
}

#[composable]
fn chains3_07_00() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_07_01() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_07_02() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_07_03() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .clip_to_bounds()
            .padding(6.0),
    );
}

#[composable]
fn chains3_07_04() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .clip_to_bounds()
            .background(RED),
    );
}

#[composable]
fn chains3_07_05() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .clip_to_bounds()
            .background(BLUE),
    );
}

#[composable]
fn chains3_07_06() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .clip_to_bounds()
            .fill_max_width(),
    );
}

#[composable]
fn chains3_07_07() {
    probe(
        Modifier::empty()
            .size_points(64.0, 44.0)
            .clip_to_bounds()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_07_08() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .padding(6.0)
            .background(RED),
    );
}

#[composable]
fn chains3_07_09() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .padding(6.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_07_10() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .padding(6.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_07_11() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .padding(6.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_07_12() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .padding(6.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_07_13() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(RED)
            .padding(6.0),
    );
}

#[composable]
fn chains3_07_14() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(RED)
            .background(BLUE),
    );
}

#[composable]
fn chains3_07_15() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(RED)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_08() {
    grid(&[
        chains3_08_00,
        chains3_08_01,
        chains3_08_02,
        chains3_08_03,
        chains3_08_04,
        chains3_08_05,
        chains3_08_06,
        chains3_08_07,
        chains3_08_08,
        chains3_08_09,
        chains3_08_10,
        chains3_08_11,
        chains3_08_12,
        chains3_08_13,
        chains3_08_14,
        chains3_08_15,
    ]);
}

#[composable]
fn chains3_08_00() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(RED)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_08_01() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(RED)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_08_02() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(BLUE)
            .padding(6.0),
    );
}

#[composable]
fn chains3_08_03() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(BLUE)
            .background(RED),
    );
}

#[composable]
fn chains3_08_04() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(BLUE)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_08_05() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(BLUE)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_08_06() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .background(BLUE)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_08_07() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .size_points(64.0, 44.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_08_08() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .size_points(64.0, 44.0)
            .background(RED),
    );
}

#[composable]
fn chains3_08_09() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .size_points(64.0, 44.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_08_10() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_08_11() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .size_points(64.0, 44.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_08_12() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .offset(7.0, 5.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_08_13() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .offset(7.0, 5.0)
            .background(RED),
    );
}

#[composable]
fn chains3_08_14() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .offset(7.0, 5.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_08_15() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_09() {
    grid(&[
        chains3_09_00,
        chains3_09_01,
        chains3_09_02,
        chains3_09_03,
        chains3_09_04,
        chains3_09_05,
        chains3_09_06,
        chains3_09_07,
        chains3_09_08,
        chains3_09_09,
        chains3_09_10,
        chains3_09_11,
        chains3_09_12,
        chains3_09_13,
        chains3_09_14,
        chains3_09_15,
    ]);
}

#[composable]
fn chains3_09_00() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .offset(7.0, 5.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_09_01() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .clip_to_bounds()
            .padding(6.0),
    );
}

#[composable]
fn chains3_09_02() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .clip_to_bounds()
            .background(RED),
    );
}

#[composable]
fn chains3_09_03() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .clip_to_bounds()
            .background(BLUE),
    );
}

#[composable]
fn chains3_09_04() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .clip_to_bounds()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_09_05() {
    probe(
        Modifier::empty()
            .fill_max_width()
            .clip_to_bounds()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_09_06() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .padding(6.0)
            .background(RED),
    );
}

#[composable]
fn chains3_09_07() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .padding(6.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_09_08() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .padding(6.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_09_09() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .padding(6.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_09_10() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .padding(6.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_09_11() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(RED)
            .padding(6.0),
    );
}

#[composable]
fn chains3_09_12() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(RED)
            .background(BLUE),
    );
}

#[composable]
fn chains3_09_13() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(RED)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_09_14() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(RED)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_09_15() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(RED)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_10() {
    grid(&[
        chains3_10_00,
        chains3_10_01,
        chains3_10_02,
        chains3_10_03,
        chains3_10_04,
        chains3_10_05,
        chains3_10_06,
        chains3_10_07,
        chains3_10_08,
        chains3_10_09,
        chains3_10_10,
        chains3_10_11,
        chains3_10_12,
        chains3_10_13,
        chains3_10_14,
        chains3_10_15,
    ]);
}

#[composable]
fn chains3_10_00() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(BLUE)
            .padding(6.0),
    );
}

#[composable]
fn chains3_10_01() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(BLUE)
            .background(RED),
    );
}

#[composable]
fn chains3_10_02() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(BLUE)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_10_03() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(BLUE)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_10_04() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .background(BLUE)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_10_05() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_10_06() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0)
            .background(RED),
    );
}

#[composable]
fn chains3_10_07() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_10_08() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_10_09() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0)
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_10_10() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .fill_max_width()
            .padding(6.0),
    );
}

#[composable]
fn chains3_10_11() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .fill_max_width()
            .background(RED),
    );
}

#[composable]
fn chains3_10_12() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .fill_max_width()
            .background(BLUE),
    );
}

#[composable]
fn chains3_10_13() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .fill_max_width()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_10_14() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .fill_max_width()
            .clip_to_bounds(),
    );
}

#[composable]
fn chains3_10_15() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .clip_to_bounds()
            .padding(6.0),
    );
}

#[composable]
fn chains3_11() {
    grid(&[
        chains3_11_00,
        chains3_11_01,
        chains3_11_02,
        chains3_11_03,
        chains3_11_04,
        chains3_11_05,
        chains3_11_06,
        chains3_11_07,
        chains3_11_08,
        chains3_11_09,
        chains3_11_10,
        chains3_11_11,
        chains3_11_12,
        chains3_11_13,
        chains3_11_14,
        chains3_11_15,
    ]);
}

#[composable]
fn chains3_11_00() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .clip_to_bounds()
            .background(RED),
    );
}

#[composable]
fn chains3_11_01() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .clip_to_bounds()
            .background(BLUE),
    );
}

#[composable]
fn chains3_11_02() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .clip_to_bounds()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_11_03() {
    probe(
        Modifier::empty()
            .offset(7.0, 5.0)
            .clip_to_bounds()
            .fill_max_width(),
    );
}

#[composable]
fn chains3_11_04() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .padding(6.0)
            .background(RED),
    );
}

#[composable]
fn chains3_11_05() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .padding(6.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_11_06() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .padding(6.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_11_07() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .padding(6.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_11_08() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .padding(6.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_11_09() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(RED)
            .padding(6.0),
    );
}

#[composable]
fn chains3_11_10() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(RED)
            .background(BLUE),
    );
}

#[composable]
fn chains3_11_11() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(RED)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_11_12() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(RED)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_11_13() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(RED)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_11_14() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(BLUE)
            .padding(6.0),
    );
}

#[composable]
fn chains3_11_15() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(BLUE)
            .background(RED),
    );
}

#[composable]
fn chains3_12() {
    grid(&[
        chains3_12_00,
        chains3_12_01,
        chains3_12_02,
        chains3_12_03,
        chains3_12_04,
        chains3_12_05,
        chains3_12_06,
        chains3_12_07,
        chains3_12_08,
        chains3_12_09,
        chains3_12_10,
        chains3_12_11,
        chains3_12_12,
        chains3_12_13,
        chains3_12_14,
        chains3_12_15,
    ]);
}

#[composable]
fn chains3_12_00() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(BLUE)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_12_01() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(BLUE)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_12_02() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .background(BLUE)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_12_03() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .size_points(64.0, 44.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_12_04() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .size_points(64.0, 44.0)
            .background(RED),
    );
}

#[composable]
fn chains3_12_05() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .size_points(64.0, 44.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_12_06() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .size_points(64.0, 44.0)
            .fill_max_width(),
    );
}

#[composable]
fn chains3_12_07() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .size_points(64.0, 44.0)
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_12_08() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .fill_max_width()
            .padding(6.0),
    );
}

#[composable]
fn chains3_12_09() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .fill_max_width()
            .background(RED),
    );
}

#[composable]
fn chains3_12_10() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .fill_max_width()
            .background(BLUE),
    );
}

#[composable]
fn chains3_12_11() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .fill_max_width()
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_12_12() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .fill_max_width()
            .offset(7.0, 5.0),
    );
}

#[composable]
fn chains3_12_13() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .offset(7.0, 5.0)
            .padding(6.0),
    );
}

#[composable]
fn chains3_12_14() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .offset(7.0, 5.0)
            .background(RED),
    );
}

#[composable]
fn chains3_12_15() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .offset(7.0, 5.0)
            .background(BLUE),
    );
}

#[composable]
fn chains3_13() {
    grid(&[chains3_13_00, chains3_13_01]);
}

#[composable]
fn chains3_13_00() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .offset(7.0, 5.0)
            .size_points(64.0, 44.0),
    );
}

#[composable]
fn chains3_13_01() {
    probe(
        Modifier::empty()
            .clip_to_bounds()
            .offset(7.0, 5.0)
            .fill_max_width(),
    );
}

#[composable]
fn text2_00() {
    grid(&[
        text2_00_00,
        text2_00_01,
        text2_00_02,
        text2_00_03,
        text2_00_04,
        text2_00_05,
        text2_00_06,
        text2_00_07,
        text2_00_08,
        text2_00_09,
        text2_00_10,
        text2_00_11,
        text2_00_12,
        text2_00_13,
        text2_00_14,
        text2_00_15,
    ]);
}

#[composable]
fn text2_00_00() {
    Text(
        "Ag Text",
        Modifier::empty()
            .padding(6.0)
            .padding_each(10.0, 2.0, 4.0, 8.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_01() {
    Text(
        "Ag Text",
        Modifier::empty().padding(6.0).background(RED),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_02() {
    Text(
        "Ag Text",
        Modifier::empty().padding(6.0).size_points(64.0, 44.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_03() {
    Text(
        "Ag Text",
        Modifier::empty().padding(6.0).width(52.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_04() {
    Text(
        "Ag Text",
        Modifier::empty().padding(6.0).fill_max_width(),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_05() {
    Text(
        "Ag Text",
        Modifier::empty().padding(6.0).offset(7.0, 5.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_06() {
    Text(
        "Ag Text",
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .padding(6.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_07() {
    Text(
        "Ag Text",
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .background(RED),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_08() {
    Text(
        "Ag Text",
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .size_points(64.0, 44.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_09() {
    Text(
        "Ag Text",
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .width(52.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_10() {
    Text(
        "Ag Text",
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .fill_max_width(),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_11() {
    Text(
        "Ag Text",
        Modifier::empty()
            .padding_each(10.0, 2.0, 4.0, 8.0)
            .offset(7.0, 5.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_12() {
    Text(
        "Ag Text",
        Modifier::empty().background(RED).padding(6.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_13() {
    Text(
        "Ag Text",
        Modifier::empty()
            .background(RED)
            .padding_each(10.0, 2.0, 4.0, 8.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_14() {
    Text(
        "Ag Text",
        Modifier::empty().background(RED).size_points(64.0, 44.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_00_15() {
    Text(
        "Ag Text",
        Modifier::empty().background(RED).width(52.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01() {
    grid(&[
        text2_01_00,
        text2_01_01,
        text2_01_02,
        text2_01_03,
        text2_01_04,
        text2_01_05,
        text2_01_06,
        text2_01_07,
        text2_01_08,
        text2_01_09,
        text2_01_10,
        text2_01_11,
        text2_01_12,
        text2_01_13,
        text2_01_14,
        text2_01_15,
    ]);
}

#[composable]
fn text2_01_00() {
    Text(
        "Ag Text",
        Modifier::empty().background(RED).fill_max_width(),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_01() {
    Text(
        "Ag Text",
        Modifier::empty().background(RED).offset(7.0, 5.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_02() {
    Text(
        "Ag Text",
        Modifier::empty().size_points(64.0, 44.0).padding(6.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_03() {
    Text(
        "Ag Text",
        Modifier::empty()
            .size_points(64.0, 44.0)
            .padding_each(10.0, 2.0, 4.0, 8.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_04() {
    Text(
        "Ag Text",
        Modifier::empty().size_points(64.0, 44.0).background(RED),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_05() {
    Text(
        "Ag Text",
        Modifier::empty().size_points(64.0, 44.0).width(52.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_06() {
    Text(
        "Ag Text",
        Modifier::empty().size_points(64.0, 44.0).fill_max_width(),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_07() {
    Text(
        "Ag Text",
        Modifier::empty().size_points(64.0, 44.0).offset(7.0, 5.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_08() {
    Text(
        "Ag Text",
        Modifier::empty().width(52.0).padding(6.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_09() {
    Text(
        "Ag Text",
        Modifier::empty()
            .width(52.0)
            .padding_each(10.0, 2.0, 4.0, 8.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_10() {
    Text(
        "Ag Text",
        Modifier::empty().width(52.0).background(RED),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_11() {
    Text(
        "Ag Text",
        Modifier::empty().width(52.0).size_points(64.0, 44.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_12() {
    Text(
        "Ag Text",
        Modifier::empty().width(52.0).fill_max_width(),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_13() {
    Text(
        "Ag Text",
        Modifier::empty().width(52.0).offset(7.0, 5.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_14() {
    Text(
        "Ag Text",
        Modifier::empty().fill_max_width().padding(6.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_01_15() {
    Text(
        "Ag Text",
        Modifier::empty()
            .fill_max_width()
            .padding_each(10.0, 2.0, 4.0, 8.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02() {
    grid(&[
        text2_02_00,
        text2_02_01,
        text2_02_02,
        text2_02_03,
        text2_02_04,
        text2_02_05,
        text2_02_06,
        text2_02_07,
        text2_02_08,
        text2_02_09,
    ]);
}

#[composable]
fn text2_02_00() {
    Text(
        "Ag Text",
        Modifier::empty().fill_max_width().background(RED),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_01() {
    Text(
        "Ag Text",
        Modifier::empty().fill_max_width().size_points(64.0, 44.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_02() {
    Text(
        "Ag Text",
        Modifier::empty().fill_max_width().width(52.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_03() {
    Text(
        "Ag Text",
        Modifier::empty().fill_max_width().offset(7.0, 5.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_04() {
    Text(
        "Ag Text",
        Modifier::empty().offset(7.0, 5.0).padding(6.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_05() {
    Text(
        "Ag Text",
        Modifier::empty()
            .offset(7.0, 5.0)
            .padding_each(10.0, 2.0, 4.0, 8.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_06() {
    Text(
        "Ag Text",
        Modifier::empty().offset(7.0, 5.0).background(RED),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_07() {
    Text(
        "Ag Text",
        Modifier::empty().offset(7.0, 5.0).size_points(64.0, 44.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_08() {
    Text(
        "Ag Text",
        Modifier::empty().offset(7.0, 5.0).width(52.0),
        TextStyle::default(),
    );
}

#[composable]
fn text2_02_09() {
    Text(
        "Ag Text",
        Modifier::empty().offset(7.0, 5.0).fill_max_width(),
        TextStyle::default(),
    );
}

#[composable]
fn rows_00() {
    grid(&[
        rows_00_00, rows_00_01, rows_00_02, rows_00_03, rows_00_04, rows_00_05, rows_00_06,
        rows_00_07, rows_00_08, rows_00_09, rows_00_10, rows_00_11, rows_00_12, rows_00_13,
        rows_00_14, rows_00_15,
    ]);
}

#[composable]
fn rows_00_00() {
    row_probe(LinearArrangement::Start, VerticalAlignment::Top);
}

#[composable]
fn rows_00_01() {
    row_probe(
        LinearArrangement::Start,
        VerticalAlignment::CenterVertically,
    );
}

#[composable]
fn rows_00_02() {
    row_probe(LinearArrangement::Start, VerticalAlignment::Bottom);
}

#[composable]
fn rows_00_03() {
    row_probe(LinearArrangement::End, VerticalAlignment::Top);
}

#[composable]
fn rows_00_04() {
    row_probe(LinearArrangement::End, VerticalAlignment::CenterVertically);
}

#[composable]
fn rows_00_05() {
    row_probe(LinearArrangement::End, VerticalAlignment::Bottom);
}

#[composable]
fn rows_00_06() {
    row_probe(LinearArrangement::Center, VerticalAlignment::Top);
}

#[composable]
fn rows_00_07() {
    row_probe(
        LinearArrangement::Center,
        VerticalAlignment::CenterVertically,
    );
}

#[composable]
fn rows_00_08() {
    row_probe(LinearArrangement::Center, VerticalAlignment::Bottom);
}

#[composable]
fn rows_00_09() {
    row_probe(LinearArrangement::SpaceBetween, VerticalAlignment::Top);
}

#[composable]
fn rows_00_10() {
    row_probe(
        LinearArrangement::SpaceBetween,
        VerticalAlignment::CenterVertically,
    );
}

#[composable]
fn rows_00_11() {
    row_probe(LinearArrangement::SpaceBetween, VerticalAlignment::Bottom);
}

#[composable]
fn rows_00_12() {
    row_probe(LinearArrangement::SpaceAround, VerticalAlignment::Top);
}

#[composable]
fn rows_00_13() {
    row_probe(
        LinearArrangement::SpaceAround,
        VerticalAlignment::CenterVertically,
    );
}

#[composable]
fn rows_00_14() {
    row_probe(LinearArrangement::SpaceAround, VerticalAlignment::Bottom);
}

#[composable]
fn rows_00_15() {
    row_probe(LinearArrangement::SpaceEvenly, VerticalAlignment::Top);
}

#[composable]
fn rows_01() {
    grid(&[rows_01_00, rows_01_01, rows_01_02, rows_01_03, rows_01_04]);
}

#[composable]
fn rows_01_00() {
    row_probe(
        LinearArrangement::SpaceEvenly,
        VerticalAlignment::CenterVertically,
    );
}

#[composable]
fn rows_01_01() {
    row_probe(LinearArrangement::SpaceEvenly, VerticalAlignment::Bottom);
}

#[composable]
fn rows_01_02() {
    row_probe(LinearArrangement::SpacedBy(7.0), VerticalAlignment::Top);
}

#[composable]
fn rows_01_03() {
    row_probe(
        LinearArrangement::SpacedBy(7.0),
        VerticalAlignment::CenterVertically,
    );
}

#[composable]
fn rows_01_04() {
    row_probe(LinearArrangement::SpacedBy(7.0), VerticalAlignment::Bottom);
}

#[composable]
fn columns_00() {
    grid(&[
        columns_00_00,
        columns_00_01,
        columns_00_02,
        columns_00_03,
        columns_00_04,
        columns_00_05,
        columns_00_06,
        columns_00_07,
        columns_00_08,
        columns_00_09,
        columns_00_10,
        columns_00_11,
        columns_00_12,
        columns_00_13,
        columns_00_14,
        columns_00_15,
    ]);
}

#[composable]
fn columns_00_00() {
    column_probe(LinearArrangement::Start, HorizontalAlignment::Start);
}

#[composable]
fn columns_00_01() {
    column_probe(
        LinearArrangement::Start,
        HorizontalAlignment::CenterHorizontally,
    );
}

#[composable]
fn columns_00_02() {
    column_probe(LinearArrangement::Start, HorizontalAlignment::End);
}

#[composable]
fn columns_00_03() {
    column_probe(LinearArrangement::End, HorizontalAlignment::Start);
}

#[composable]
fn columns_00_04() {
    column_probe(
        LinearArrangement::End,
        HorizontalAlignment::CenterHorizontally,
    );
}

#[composable]
fn columns_00_05() {
    column_probe(LinearArrangement::End, HorizontalAlignment::End);
}

#[composable]
fn columns_00_06() {
    column_probe(LinearArrangement::Center, HorizontalAlignment::Start);
}

#[composable]
fn columns_00_07() {
    column_probe(
        LinearArrangement::Center,
        HorizontalAlignment::CenterHorizontally,
    );
}

#[composable]
fn columns_00_08() {
    column_probe(LinearArrangement::Center, HorizontalAlignment::End);
}

#[composable]
fn columns_00_09() {
    column_probe(LinearArrangement::SpaceBetween, HorizontalAlignment::Start);
}

#[composable]
fn columns_00_10() {
    column_probe(
        LinearArrangement::SpaceBetween,
        HorizontalAlignment::CenterHorizontally,
    );
}

#[composable]
fn columns_00_11() {
    column_probe(LinearArrangement::SpaceBetween, HorizontalAlignment::End);
}

#[composable]
fn columns_00_12() {
    column_probe(LinearArrangement::SpaceAround, HorizontalAlignment::Start);
}

#[composable]
fn columns_00_13() {
    column_probe(
        LinearArrangement::SpaceAround,
        HorizontalAlignment::CenterHorizontally,
    );
}

#[composable]
fn columns_00_14() {
    column_probe(LinearArrangement::SpaceAround, HorizontalAlignment::End);
}

#[composable]
fn columns_00_15() {
    column_probe(LinearArrangement::SpaceEvenly, HorizontalAlignment::Start);
}

#[composable]
fn columns_01() {
    grid(&[
        columns_01_00,
        columns_01_01,
        columns_01_02,
        columns_01_03,
        columns_01_04,
    ]);
}

#[composable]
fn columns_01_00() {
    column_probe(
        LinearArrangement::SpaceEvenly,
        HorizontalAlignment::CenterHorizontally,
    );
}

#[composable]
fn columns_01_01() {
    column_probe(LinearArrangement::SpaceEvenly, HorizontalAlignment::End);
}

#[composable]
fn columns_01_02() {
    column_probe(LinearArrangement::SpacedBy(7.0), HorizontalAlignment::Start);
}

#[composable]
fn columns_01_03() {
    column_probe(
        LinearArrangement::SpacedBy(7.0),
        HorizontalAlignment::CenterHorizontally,
    );
}

#[composable]
fn columns_01_04() {
    column_probe(LinearArrangement::SpacedBy(7.0), HorizontalAlignment::End);
}

#[composable]
fn boxes_00() {
    grid(&[
        boxes_00_00,
        boxes_00_01,
        boxes_00_02,
        boxes_00_03,
        boxes_00_04,
        boxes_00_05,
        boxes_00_06,
        boxes_00_07,
        boxes_00_08,
    ]);
}

#[composable]
fn boxes_00_00() {
    box_probe(Alignment::new(
        HorizontalAlignment::Start,
        VerticalAlignment::Top,
    ));
}

#[composable]
fn boxes_00_01() {
    box_probe(Alignment::new(
        HorizontalAlignment::CenterHorizontally,
        VerticalAlignment::Top,
    ));
}

#[composable]
fn boxes_00_02() {
    box_probe(Alignment::new(
        HorizontalAlignment::End,
        VerticalAlignment::Top,
    ));
}

#[composable]
fn boxes_00_03() {
    box_probe(Alignment::new(
        HorizontalAlignment::Start,
        VerticalAlignment::CenterVertically,
    ));
}

#[composable]
fn boxes_00_04() {
    box_probe(Alignment::new(
        HorizontalAlignment::CenterHorizontally,
        VerticalAlignment::CenterVertically,
    ));
}

#[composable]
fn boxes_00_05() {
    box_probe(Alignment::new(
        HorizontalAlignment::End,
        VerticalAlignment::CenterVertically,
    ));
}

#[composable]
fn boxes_00_06() {
    box_probe(Alignment::new(
        HorizontalAlignment::Start,
        VerticalAlignment::Bottom,
    ));
}

#[composable]
fn boxes_00_07() {
    box_probe(Alignment::new(
        HorizontalAlignment::CenterHorizontally,
        VerticalAlignment::Bottom,
    ));
}

#[composable]
fn boxes_00_08() {
    box_probe(Alignment::new(
        HorizontalAlignment::End,
        VerticalAlignment::Bottom,
    ));
}

#[composable]
fn weights_00() {
    grid(&[
        weights_00_00,
        weights_00_01,
        weights_00_02,
        weights_00_03,
        weights_00_04,
        weights_00_05,
        weights_00_06,
        weights_00_07,
    ]);
}

#[composable]
fn weights_00_00() {
    weights_probe(&[(1.0, true), (1.0, true)]);
}

#[composable]
fn weights_00_01() {
    weights_probe(&[(1.0, true), (2.0, true)]);
}

#[composable]
fn weights_00_02() {
    weights_probe(&[(1.0, true), (0.0, true), (1.0, true)]);
}

#[composable]
fn weights_00_03() {
    weights_probe(&[(1.0, false), (1.0, true)]);
}

#[composable]
fn weights_00_04() {
    weights_probe(&[(1.0, true), (1.0, true), (1.0, true)]);
}

#[composable]
fn weights_00_05() {
    weights_probe(&[(0.0, true), (3.0, true), (0.0, true)]);
}

#[composable]
fn weights_00_06() {
    weights_probe(&[(1.0, false), (2.0, false)]);
}

#[composable]
fn weights_00_07() {
    weights_probe(&[
        (1.0, true),
        (1.0, true),
        (1.0, true),
        (1.0, true),
        (1.0, true),
        (1.0, true),
        (1.0, true),
    ]);
}
