[package]
name = "coroflow"
description = "Kotlin-style coroutines and Flow for Rust, independent of any async runtime"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
futures-core = "0.3.32"
log = "0.4"
thiserror = "2"

[lints]
workspace = true

[dev-dependencies]
pollster = "0.4"
stats_alloc = "0.1.10"
