[package]
name = "cranpose-capabilities"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description = "Declare platform services, permissions and hardware for Cranpose apps"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[[bin]]
name = "cranpose-plist"
path = "src/bin/cranpose_plist.rs"
