[package]
name = "cranpose-animation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description = "Animation system for Cranpose"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
cranpose-core = { workspace = true, features = ["internal"] }
cranpose-ui-graphics = { workspace = true }

[features]
default = []
